name: lando-frontjs
proxy:
  node:
    - frontjs.lndo.site:8022
services:
  node:
    type: node:14
    build:
      - yarn install
    scanner: false
    ssl: false
    sslExpose: false
    overrides:
      ports:
        - 8022:8022
tooling:
  node:
    service: node
  yarn:
    service: node
  dev:
    service: node
    cmd: yarn serve --port 8022
